name: StadtServer
version: 1.10.4
author: mfk1016
main: me.mfk1016.stadtserver.StadtServer
api-version: 1.18
depend: [ ProtocolLib ]

commands:
  stadtserver:
    description: Configuration and Debugging
    usage: /stadtserver [ config reload/reset || book ench level || boss type level || ancient ]